# fly.toml app configuration file generated for pyhon-processor on 2025-10-19T08:44:21+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pyhon-processor'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
